
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: model-pipeline # executable id, must be unique across all your workflows (YAML files)
  annotations:
    scenarios.ai.sap.com/description: "Learning how save a model workflow"
    scenarios.ai.sap.com/name: "Iris Model (Tutorial)" # Scenario name should be the use case
    executables.ai.sap.com/description: "Train with live data"
    executables.ai.sap.com/name: "training" # Executable name should describe the workflow in the use case
    artifacts.ai.sap.com/irismodel.kind: "model" # Helps in suggesting the kind of artifact that can be generated.
  labels:
    scenarios.ai.sap.com/id: "learning-model"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: juliodockerregistry # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1
  - name: mycodeblock1
    outputs:
      artifacts:
        - name: irisdummymodel # name of the artifact generated, and folder name when placed in S3, complete directory will be `../<executaion_id>/housepricemodel`
          globalName: irismodel # local identifier name to the workflow, also used above in annotation
          path: /app/model/ # from which folder in docker image (after running workflow step) copy contents to cloud storage
          archive:
            none:   # specify not to compress while uploading to cloud
              {}
    container:
      image: docker.io/juliobernardes/dummy-model:01 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/train.py"
